language: python
sudo: false  

branches:
  only:
    - master

python:
  - "3.5"

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=cover

cache:
  directories:
    - elm-stuff/build-artifacts

install:
  - npm i -g elm
  - elm-package install --yes
  - pip install tox     

script:
  - tox

after_success:
  - coveralls
