language: python
sudo: false  

branches:
  only:
    - master

python:
  - "3.6-dev"

env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=cover

install:
  - npm i -g elm
  - elm-package install --yes
  - pip install tox     

script:
  - tox

after_success:
  - coveralls
